name = "workers-graphql-typescript-d1"
main = "./src/index.ts"
compatibility_date = "2022-08-17"
node_compat = true

[[ d1_databases ]]
binding = "database" # i.e. available in your Worker on env.DB
database_name = "wgtd"
database_id = "9c886fe6-de7c-4ea4-8964-8de05aa53b55"
preview_database_id = "9c886fe6-de7c-4ea4-8964-8de05aa53b55"